chajia-webapp/config/routes.rb
Cp::Application.routes.draw do
  root to: 'products#home'
  resources :products

  

end

chajia-webapp/app/models/price.rb
class Price < ActiveRecord::Base
	belongs_to :product
end

chajia-webapp/app/models/product.rb
class Product < ActiveRecord::Base
	has_many :prices,dependent: :destroy
end

chajia-webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

chajia-webapp/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'nokogiri'
  require 'open-uri'
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def home

  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    content =params[:content]
    pid=/\d+/.match(/[?,&]id=\d+\&/.match(content)[0]).to_s
    #如果不是通过url 那通过title来的查找 
    
    # print pid
    @product = Product.find_by(pid: pid)
    if @product==nil

      page = Nokogiri::HTML(open("http://s.etao.com/detail/#{@pid}.html"))
      title=page.css(".product-title")[0]['title']
      url = 'http://s.etao.com/detail/#{@pid}.html'
      img=page.css('.product-picture')[0]['img-src']
      price=page.css('.original-price')[0].text[1..-1]
      @product = Product.new(pid: pid,title: title ,url: url, img: img)
      @price = Price.new(pid: pid,price: price)

      respond_to do |format|

      if @product.save && @price.save
        format.html { redirect_to root_path, notice: 'Product was successfully created.' }
        format.js
        return 
      else
        format.html { render action: 'new' }
        format.js
        return
      end
    end

    else 
      @prices =@product.prices
      #redirect_to root_path
      return

    end


    
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:pid, :title, :img, :price)
  end
end

chajia-webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

chajia-webapp/app/helpers/products_helper.rb
module ProductsHelper
end

chajia-webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cp</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container ">
	<%= yield %>
</div>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

chajia-webapp/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br>
    <%= f.number_field :pid %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

chajia-webapp/app/views/products/create.js.erb
$('#result').show();
function makeHead(){
    $("#rearch_head").css({ width: "100%",heigth:"80px", background:"url(img/header_bg.png)" });
    $("#rearch_head").addClass("navbar-fixed-top");
}
$(".search").animate({marginTop: '5px'}, "slow",makeHead);
$(".search").css({marginBottom: "10px"});
$("#result").css({marginTop: "50px"});
$('#title').attr('href', 'http://detail.tmall.com/item.htm?id=<%= @product.pid %>');
// $("#img1").attr('src', '<%= @product.img %>_350x350.jpg');
$('#title').html('<%= @product.title %>');
$('#price').html('￥<%= @prices[0].price %>');
// $("#img").attr("src", '<%= @product.img %>_350x350.jpg');
// $("#img").attr("src", 'http://192.168.56.101:3000/img/p.png');
// $('.carousel').carousel({
//   interval: 2000
// });

$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
$('#carousel').append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');

function clickImg(el, position, evt){
    alert("haha");
    return 0;

}
$('#carousel').elastislide({onClick : clickImg});
// var Carousels = function(){
//     return {
//         add :function() {
//           var carouselEl =$('#carousel'),carousel=carouselEl.elastislide();
//             carouselEl.append('<li><a href="#"><img src="<%= @product.img %>_350x350.jpg" alt="image03" /></a></li>');
//             carousel.add();  
//         }
//     };
// }();
var Charts = function() {

    return {
        //main function to initiate the module

        init: function() {



        },

        initCharts: function() {

            if (!jQuery.plot) {
                return;
            }
            //Interactive Chart

            function chart2() {
                function randValue() {
                    return (Math.floor(Math.random() * (1 + 40 - 20))) + 20;
                }
            function gd(year, month, day) {
                    return new Date(year, month-1, day,8,0,0,0).getTime();
                }

                var prices = [];
                var sales = [];
                <% @prices.each do |p | %>
                <% @date=Date.parse(p.created_at.to_s[0,10]) %>                      
                prices.push([gd(<%=@date.year%>,<%=@date.mon%>,<%=@date.mday%>),<%=p.price%>]);
                sales.push([gd(<%=@date.year%>,<%=@date.mon%>,<%=@date.mday%>),randValue()- 5]);
                <% end %>
               
                var plot = $.plot($("#chart_2"), [{
                    data: sales,
                    label: "销量",
                    yaxis: 2
                }, {
                    data: prices,
                    label: "价格"
                }], {
                    series: {
                        lines: {
                            show: true,
                            lineWidth: 2,
                            fill: true,
                            fillColor: {
                                colors: [{
                                    opacity: 0.05
                                }, {
                                    opacity: 0.01
                                }]
                            }
                        },
                        points: {
                            show: true
                        },
                        shadowSize: 2
                    },
                    grid: {
                        hoverable: true,
                        clickable: true,
                        tickColor: "#eee",
                        borderWidth: 0
                    },
                    colors: ["#d12610", "#37b7f3", "#52e136"],
                    xaxis: {
                         mode: "time",                         
                         timeformat: "%m-%d",
                         tickSize: [1,"day"]
                        
                    },
                    yaxis: {
                        ticks: 5,
                        tickDecimals: 0
                    },
                    xaxes: [{ position: "bottom" }],
                    yaxes: [{ position: "left" }, { position: "right"}]
                });


                function showTooltip(x, y, contents) {
                    $('<div id="tooltip">' + contents + '</div>').css({
                        position: 'absolute',
                        display: 'none',
                        top: y + 5,
                        left: x + 15,
                        border: '1px solid #333',
                        padding: '4px',
                        color: '#fff',
                        'border-radius': '3px',
                        'background-color': '#333',
                        opacity: 0.80
                    }).appendTo("body").fadeIn(200);
                }

                var previousPoint = null;
                $("#chart_2").bind("plothover", function(event, pos, item) {
                    // $("#x").text(pos.x.toFixed(2));
                    // console.log(pos);
                    // $("#y").text(pos.y.toFixed(2));

                    if (item) {
                        if (previousPoint != item.dataIndex) {
                            previousPoint = item.dataIndex;

                            $("#tooltip").remove();
                            if (item.series.label == '销量') {
                                var x = item.datapoint[0],
                                    y = item.datapoint[1],
                                    date = new Date(x),
                                    content=  "<strong>" + item.series.label + "</strong><br>"  +
                                               (date.getMonth() + 1) + "月" + date.getDate()+"日" +
                            " : <strong>" + y + "</strong> (件)";    
                            } else {
                                var x = item.datapoint[0],
                                    y = item.datapoint[1].toFixed(2),
                                    date = new Date(x),
                                    content=  "<strong>" + item.series.label + "</strong><br>"  +
                                               (date.getMonth() + 1) + "月" + date.getDate() +"日"+
                                                " : <strong>" + y + "</strong> (元)"; 

                            }


                            showTooltip(item.pageX, item.pageY,content);
                        }
                    } else {
                        $("#tooltip").remove();
                        previousPoint = null;
                    }
                });
            }
            //graph
            chart2();
        },
    };

}();


Charts.init();
Charts.initCharts();
// Carousels.add();

chajia-webapp/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

chajia-webapp/app/views/products/home.html.erb
<div id="rearch_head">
    

<div class="row search" >
    <div class="col-md-8 col-md-offset-3">	
    <%= form_tag('/products' ,:method => :post,:class => 'form-inline' ,:role=>"form" ,:remote=> true) do %>			
    <div class="form-group col-md-7 ">
            <input class='form-control' type='text' name='content' >
    </div>
            <button type='submit' class= "btn btn-large btn-primary">查价 </button>
    <% end %>
    </div>
</div>
</div>

<div id="result">
    <div class="row" id="b2">
        <div class="col-md-8 col-md-offset-1">
        	<a id="title"  href='#'></a>
        </div>   
        <div class="col-md-2">天猫商城</div> 	    	
    </div>    
     <div class="row" id="b3">
            <div class="col-md-9 ">
                <ul id="carousel" class="elastislide-list">

                </ul>                
            </div>
             <div class="col-md-3">
                 <div>当前价格：</div>
                 <div id="price"></div>
                 <button class="btn btn-large btn-primary">前去购买</button>
             </div>
         </div>
    <div class="row" id="b4">            
    <!-- BEGIN INTERACTIVE CHART PORTLET-->
            <div class="portlet box red col-md-12">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-reorder"></i>价格曲线图</div>
                </div>
                <div class="portlet-body">
                    <div id="chart_2" class="chart"></div>
                </div>
            </div>
    <!-- END INTERACTIVE CHART PORTLET-->  
    </div>
    
</div>

chajia-webapp/app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Pid</th>
      <th>Title</th>
      <th>Img</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.pid %></td>
        <td><%= product.title %></td>
        <td><%= product.img %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

chajia-webapp/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

chajia-webapp/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @product.pid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Img:</strong>
  <%= image_tag @product.img %>
</p>

<p>
  <strong>Price:</strong>
  ￥<%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>